[package]
name = "parser-on-rust"
version = "0.1.1"
edition = "2021"
description = "parser on rust"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.2"
